### ISSUE TITLE
tmc5160

### ISSUE THREAD

**Issue by matthew73210** [tommag/Estee_TMC5130#2]
Just a note, this will also work for the tmc5160 as they share the same logic. Good idea if you added it.

**Comment by tommag** [comment]
Thanks for your comment ! 

I'm actually working with TMC5160 as well and have a local library working, I just have to take some time to merge the two code bases. I'll post a comment here when it's done, it will probably be a different repository to avoid backwards compatibility needs.

**Comment by shreeramlive** [comment]
@tommag You have created a great library for Arduino. Thanks for sharing it with the community.

**Comment by tommag** [comment]
I've just published the TMC5160 lib here : https://github.com/tommag/TMC5160_Arduino
